/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class DependencySizeReportPluginTest {
    @Test
    void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("dependency-size-report");

        // Verify the result
        assertNotNull(project.getTasks().findByName("dependencySize"));
    }
}
