/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple functional test for the 'org.example.greeting' plugin.
 */
class DependencySizeReportPluginFunctionalTest {
    private Path getBuildFile(Path projectDir) {
        return projectDir.resolve("build.gradle");
    }

    private Path getSettingsFile(Path projectDir) {
        return projectDir.resolve("settings.gradle");
    }

    @Test void canRunTask(@TempDir Path projectDir) throws IOException {
        writeString(getSettingsFile(projectDir), "");
        writeString(getBuildFile(projectDir),
                """
                        plugins {
                          id('java')
                          id('dependency-size-report')
                        }
                        repositories {
                          mavenCentral()
                        }
                        dependencies {
                          implementation('com.google.guava:guava:33.5.0-jre')
                        }
                        """);

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("dependencySize");
        runner.withProjectDir(projectDir.toFile());
        BuildResult result = runner.build();
        BuildResult rerunResult = runner.build();

        // Verify the result
        var task = result.task(":dependencySize");
        assertNotNull(task);
        assertEquals(TaskOutcome.SUCCESS, task.getOutcome());

        var rerunTask = rerunResult.task(":dependencySize");
        assertNotNull(rerunTask);
        assertEquals(TaskOutcome.UP_TO_DATE, rerunTask.getOutcome());
    }

    private void writeString(Path file, String string) throws IOException {
        Files.writeString(file, string);
    }
}
