/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.BuildResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * A simple functional test for the 'org.example.greeting' plugin.
 */
class GradleDependencyDownloaderPluginFunctionalTest {
    //@TempDir
    //File projectDir;

    private Path getBuildFile(Path projectDir) {
        return projectDir.resolve("build.gradle");
    }

    private Path getSettingsFile(Path projectDir) {
        return projectDir.resolve("settings.gradle");
    }

    @Test void canRunTask(@TempDir Path projectDir) throws IOException {
        writeString(getSettingsFile(projectDir), "");
        writeString(getBuildFile(projectDir),
                """
                        plugins {
                          id('dependency-size-insight')
                        }
                        """);

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("greeting");
        runner.withProjectDir(projectDir.toFile());
        BuildResult result = runner.build();

        // Verify the result
        assertTrue(result.getOutput().contains("Hello from plugin 'org.example.greeting'"));
    }

    private void writeString(Path file, String string) throws IOException {
        Files.writeString(file, string);
    }
}
