/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.gradle.api.NamedDomainObjectProvider;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.artifacts.Configuration;
import org.gradle.api.artifacts.type.ArtifactTypeDefinition;
import org.gradle.api.tasks.TaskProvider;
import org.jspecify.annotations.NonNull;

/**
 * A simple 'hello world' plugin.
 */
public abstract class DependencySizeReportPlugin implements Plugin<Project> {

    public static final String DEPENDENCY_SIZE_CONFIGURATION_NAME = "dependencySize";

    public void apply(Project project) {
        project.getPlugins().apply(DependencySizeBasePlugin.class);
        NamedDomainObjectProvider<Configuration> dependencySizeConfiguration = project.getConfigurations().register(DEPENDENCY_SIZE_CONFIGURATION_NAME, (conf) -> {
            conf.attributes(attributes -> {
                attributes.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, "binary");
            });
        });
        NamedDomainObjectProvider<Configuration> dependencySizeTooling = project.getConfigurations().named("dependencySizeTooling");
        TaskProvider<@NonNull DependencySizeTask> dependencySizeTask = project.getTasks().register("dependencySize", DependencySizeTask.class, task -> {
            task.getWorkerClasspath().from(dependencySizeTooling);
        });
        project.artifacts(artifactHandler -> {
            artifactHandler.add(dependencySizeConfiguration.getName(), dependencySizeTask);
        });
    }
}
